config/routes.rb
Rails.application.routes.draw do
  root "shops#index"
  resources :shops, only: [:index, :show] do
    resources :puppies, only: [:index]
  end

  resources :users, only: [:new, :create]

  get "/dashboard",      to: "users#show"
  # get    'signup'  => ''
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/puppy.rb
class Puppy < ActiveRecord::Base
  belongs_to :shop
  belongs_to :user
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :puppies

  def average_price
    puppies.average("price").to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :puppies
  enum role: [ :customer, :store_owner ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    # @current_user ||= session[:current_user_id] &&
    # User.find_by(id: session[:current_user_id])
  end
end

app/controllers/puppies_controller.rb
class PuppiesController<ApplicationController

  def index
    @shop = Shop.find_by(id: params[:shop_id])
    @puppies = Puppy.where(shop_id: params[:shop_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController

  def new

  end

  def create
    @user = User.find_by(user_name: params[:session][:user_name])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render :new
    end
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @shops = Shop.all
    # @puppies = Puppies.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController<ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path(@user)
    else
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puppies/index.html.erb
<h1> <%=@shop.name%> </h1>
<% @puppies.each do |puppy| %>
  <ul>
  <li><%= puppy.name %></li>
  <li><%= puppy.breed %></li>
  <li><%= puppy.age %></li>
  <li><%= link_to "Add To Cart", user_cart_path(current_user) %></li>
  </ul>
<% end %>
 

app/views/shared/_dashboard.html.erb
<h1>Username: <%= current_user.user_name %></h1>
<h2>User Puppies</h2>
<ol><% current_user.puppies.each do |puppy| %>
    <li><%= puppy.name %></li>
<% end %></ol>

      <li><%= link_to "Retun Main Site", root_path %></li>
  

app/views/shops/index.html.erb
<h1>All Pet Shops</h1>

<%= link_to "Login", login_path %>
<%= link_to "Create Account", new_user_path %>

<% @shops.each do |shop| %>
  <h2><%= shop.name %></h2>
  <ul>
  <li><%= "Average Puppy price $#{shop.average_price}" %></li>
  <li><%= link_to shop.name, shop_path(shop)%></li>
</ul>
<% end %>

app/views/shops/show.html.erb
<h1><%=@shop.name%></h1>
<%=link_to "View our Puppies", shop_puppies_path(@shop) %>

app/views/users/new.html.erb
<%= form_for @user do |f|%>
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>

  <%= f.label :password %>
  <%= f.password_field :password %>
    <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<%= render "shared/dashboard", dashboard_name: "User Info" %>